apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets2
  namespace: {{ $.Release.Namespace }}
spec:
  provider: aws
  secretObjects:
    - secretName: vr-creds
      type: Opaque
      data:
        - objectName: rds-endpoint
          key: DATABASE_HOST_STRING_Secret
        - objectName: rds-password
          key: DB_PASSWORD_Secret
        - objectName: rds-user
          key: DB_USER_NAME_Secret
        - objectName: rds-name
          key: DATABASE_NAME_Secret
        - objectName: api-provider-user
          key: API_PROVIDER_USERNAME_Secret
        - objectName: api-provider-password
          key: API_PROVIDER_PASSWORD_Secret
        - objectName: app-ingestor-user
          key: APP_INGESTOR_USERNAME_Secret
        - objectName: app-ingestor-password
          key: APP_INGESTOR_PASSWORD_Secret
        - objectName: app-search-user
          key: APP_SEARCH_USERNAME_Secret
        - objectName: app-search-password
          key: APP_SEARCH_PASSWORD_Secret
        - objectName: core-service-user
          key: CORE_SERVICE_USERNAME_Secret
        - objectName: core-service-password
          key: CORE_SERVICE_PASSWORD_Secret
        - objectName: core-auth-user
          key: CORE_AUTH_USERNAME_Secret
        - objectName: core-auth-password
          key: CORE_AUTH_PASSWORD_Secret
        - objectName: multitenancy-service-user
          key: MULTITENANCY_USERNAME_Secret
        - objectName: multitenancy-service-password
          key: MULTITENANCY_PASSWORD_Secret
        - objectName: core-content-user
          key: CORE_CONTENT_USERNAME_Secret
        - objectName: core-content-password
          key: CORE_CONTENT_PASSWORD_Secret
        - objectName: core-editorial-user
          key: CORE_EDITORIAL_USERNAME_Secret
        - objectName: core-editorial-password
          key: CORE_EDITORIAL_PASSWORD_Secret
        - objectName: subscriber-mgmt-user
          key: SUBS_MGMT_USERNAME_Secret
        - objectName: subscriber-mgmt-password
          key: SUBS_MGMT_PASSWORD_Secret
        - objectName: videoready-config-user
          key: VIDEO_CONFIG_USERNAME_Secret
        - objectName: videoready-config-password
          key: VIDEO_CONFIG_PASSWORD_Secret
        - objectName: rabbit-mq-endpoint
          key: RABBITMQ_HOST_Secret
        - objectName: rabbit-mq-username
          key: RABBIT_MQ_USERNAME_Secret
        - objectName: rabbit-mq-password
          key: RABBIT_MQ_PASSWORD_Secret
        - objectName: mongodb-admin-password
          key: MONGO_PASSWORD_Secret
        - objectName: mongodb-admin-user
          key: MONGO_USERNAME_Secret
        - objectName: mongodb-db-name
          key: MONGO_DB_NAME_Secret
        - objectName: mongodb-admin-db
          key: MONGO_AUTH_DB_Secret
        - objectName: mongodb-admin-host
          key: MONGO_HOST_Secret
        - objectName: search-db-name
          key: SEARCH_DB_NAME_Secret
        - objectName: elastic-host
          key: ELASTIC_HOST_Secret
        - objectName: elastic-user
          key: ELASTIC_USER
        - objectName: elastic-password
          key: ELASTIC_PASSWORD
  parameters:
    objects: |
        - objectName: "/{{ $.Release.Namespace }}/RDS/ENDPOINT"
          objectType: "ssmparameter"
          objectAlias: rds-endpoint
        - objectName: "/{{ $.Release.Namespace }}/RDS/PASSWORD"
          objectType: "ssmparameter"
          objectAlias: rds-password
        - objectName: "/{{ $.Release.Namespace }}/RDS/USER"
          objectType: "ssmparameter"
          objectAlias: rds-user
        - objectName: "/{{ $.Release.Namespace }}/RDS/NAME"
          objectType: "ssmparameter"
          objectAlias: rds-name
        - objectName: "/{{ $.Release.Namespace }}/RDS/api-provider/USERNAME"
          objectType: "ssmparameter"
          objectAlias: api-provider-user
        - objectName: "/{{ $.Release.Namespace }}/RDS/api-provider/PASSWORD"
          objectType: "ssmparameter"
          objectAlias: api-provider-password
        - objectName: "/{{ $.Release.Namespace }}/SEARCH_DB/application-ingestor/USERNAME"
          objectType: "ssmparameter"
          objectAlias: app-ingestor-user
        - objectName: "/{{ $.Release.Namespace }}/SEARCH_DB/application-ingestor/PASSWORD"
          objectType: "ssmparameter"
          objectAlias: app-ingestor-password
        - objectName: "/{{ $.Release.Namespace }}/SEARCH_DB/application-search/USERNAME"
          objectType: "ssmparameter"
          objectAlias: app-search-user
        - objectName: "/{{ $.Release.Namespace }}/SEARCH_DB/application-search/PASSWORD"
          objectType: "ssmparameter"
          objectAlias: app-search-password
        - objectName: "/{{ $.Release.Namespace }}/RDS/core/USERNAME"
          objectType: "ssmparameter"
          objectAlias: core-service-user
        - objectName: "/{{ $.Release.Namespace }}/RDS/core/PASSWORD"
          objectType: "ssmparameter"
          objectAlias: core-service-password
        - objectName: "/{{ $.Release.Namespace }}/RDS/core-auth/USERNAME"
          objectType: "ssmparameter"
          objectAlias: core-auth-user
        - objectName: "/{{ $.Release.Namespace }}/RDS/core-auth/PASSWORD"
          objectType: "ssmparameter"
          objectAlias: core-auth-password
        - objectName: "/{{ $.Release.Namespace }}/RDS/core-content/USERNAME"
          objectType: "ssmparameter"
          objectAlias: core-content-user
        - objectName: "/{{ $.Release.Namespace }}/RDS/core-content/PASSWORD"
          objectType: "ssmparameter"
          objectAlias: core-content-password
        - objectName: "/{{ $.Release.Namespace }}/RDS/core-editorial/USERNAME"
          objectType: "ssmparameter"
          objectAlias: core-editorial-user
        - objectName: "/{{ $.Release.Namespace }}/RDS/core-editorial/PASSWORD"
          objectType: "ssmparameter"
          objectAlias: core-editorial-password
        - objectName: "/{{ $.Release.Namespace }}/RDS/subscriber-management/USERNAME"
          objectType: "ssmparameter"
          objectAlias: subscriber-mgmt-user
        - objectName: "/{{ $.Release.Namespace }}/RDS/subscriber-management/PASSWORD"
          objectType: "ssmparameter"
          objectAlias: subscriber-mgmt-password
        - objectName: "/{{ $.Release.Namespace }}/SEARCH_DB/NAME"
          objectType: "ssmparameter"
          objectAlias: search-db-name
        - objectName: "/{{ $.Release.Namespace }}/SEARCH_DB/videoready-config/USERNAME"
          objectType: "ssmparameter"
          objectAlias: videoready-config-user
        - objectName: "/{{ $.Release.Namespace }}/SEARCH_DB/videoready-config/PASSWORD"
          objectType: "ssmparameter"
          objectAlias: videoready-config-password
        - objectName: "/{{ $.Release.Namespace }}/rabbit/ENDPOINT"
          objectType: "ssmparameter"
          objectAlias: rabbit-mq-endpoint
        - objectName: "/{{ $.Release.Namespace }}/rabbit/USERNAME"
          objectType: "ssmparameter"
          objectAlias: rabbit-mq-username
        - objectName: "/{{ $.Release.Namespace }}/rabbit/PASSWORD"
          objectType: "ssmparameter"
          objectAlias: rabbit-mq-password
        - objectName: "/{{ $.Release.Namespace }}/MongoDB/MONGODB_ADMIN_PASSWORD"
          objectType: "ssmparameter"
          objectAlias: mongodb-admin-password
        - objectName: "/{{ $.Release.Namespace }}/MongoDB/ADMIN_USER"
          objectType: "ssmparameter"
          objectAlias: mongodb-admin-user
        - objectName: "/{{ $.Release.Namespace }}/MongoDB/ADMIN_DB"
          objectType: "ssmparameter"
          objectAlias: mongodb-admin-db
        - objectName: "/{{ $.Release.Namespace }}/MongoDB/MONGODB_HOST"
          objectType: "ssmparameter"
          objectAlias: mongodb-admin-host
        - objectName: "/{{ $.Release.Namespace }}/MongoDB/MONGO_DB_NAME"
          objectType: "ssmparameter"
          objectAlias: mongodb-db-name
        - objectName: "/{{ $.Release.Namespace }}/elasticsearch/host"
          objectType: "ssmparameter"
          objectAlias: elastic-host
        - objectName: "/{{ $.Release.Namespace }}/elasticsearch/USERNAME"
          objectType: "ssmparameter"
          objectAlias: elastic-user
        - objectName: "/{{ $.Release.Namespace }}/elasticsearch/PASSWORD"
          objectType: "ssmparameter"
          objectAlias: elastic-password
        