replicaCount: 1
appName: "subscriber-management"
run: "subscriber-management"

environments:
  - name: DATABASE_HOST_STRING
    valueFrom:
      secretKeyRef:
         name: vr-creds
         key: DATABASE_HOST_STRING_Secret
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
         name: vr-creds
         key: SUBS_MGMT_PASSWORD_Secret
  - name: DATABASE_NAME
    valueFrom:
      secretKeyRef:
        name: vr-creds
        key: DATABASE_NAME_Secret
  - name: DB_USER_NAME
    valueFrom:
      secretKeyRef:
         name: vr-creds
         key: SUBS_MGMT_USERNAME_Secret
  - name: MIN_HEAP
    value: "-Xms500m"
  - name: MAX_HEAP
    value: "-Xmx500m"
  - name: server.servlet.contextPath
    value: "/subscriber-gateway"
  - name: ELASTIC_HOST
    valueFrom:
      secretKeyRef:
        name: vr-creds
        key: ELASTIC_HOST_Secret
  - name: ELASTIC_USER
    value: "elastic"
  - name: ELASTIC_PASSWORD
    value: "eE8$2&91sNla"

image:
  repository: "454578700264.dkr.ecr.us-east-1.amazonaws.com/ais-poc-ais-poc-ais-subscriber-management"
  pullPolicy: Always
  tag: "latest"
  pullSecret:
    name: vr-secrets

resources:
  limits:
    cpu: 500m
    memory: 1000Mi
  requests:
    cpu: 500m
    memory: 1000Mi
  containerInfo:
    containerPort: 8006
    healthUrl: /subscriber-gateway/actuator/health
    logPath: /opt/logs/uat/subscriber-management

nameOverride: ""
fullnameOverride: ""

#serviceAccount:
#  # Specifies whether a service account should be created
#  create: true
#  # Annotations to add to the service account
#  annotations: {}
#  # The name of the service account to use.
#  # If not set and create is true, a name is generated using the fullname template
#  name: ""

podAnnotations: {}

podSecurityContext: {}
# fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
#   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000

service:
  type: ClusterIP
  port: 80

#ingress:
#  enabled: false
#  annotations: {}
#  # kubernetes.io/ingress.class: nginx
#  # kubernetes.io/tls-acme: "true"
#  hosts:
#    -   host: chart-example.local
#        paths: []
#  tls: []
#  #  - secretName: chart-example-tls
#  #    hosts:
#  #      - chart-example.local

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

#tolerations:
#  - key: "availability_zone"
#    operator: "Exists"
#    effect: "NoSchedule"
#  - key: "ec2_lifecycle"
#    operator: "Exists"
#    effect: "NoSchedule"
#  - key: "instance_type"
#    operator: "Exists"
#    effect: "NoSchedule"

affinity: {}
