kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: "{{ .Values.appName }}-service-role"
    namespace: "{{ $.Release.Namespace }}"
rules:
- apiGroups:
  - ""
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
  - create
  - delete